-- 1. b2b_products 테이블 생성
CREATE TABLE IF NOT EXISTS public.b2b_products (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price TEXT NOT NULL,
    cny_price NUMERIC,
    image TEXT NOT NULL,
    categories TEXT[] NOT NULL DEFAULT '{}',
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 기존 테이블이 있다면 cny_price 컬럼 추가
ALTER TABLE public.b2b_products ADD COLUMN IF NOT EXISTS cny_price NUMERIC;

-- RLS 정책 설정 (모든 사용자가 읽을 수 있고, 어드민만 작성 가능하게 설정할 수도 있으나, 편의상 공개 읽기 허용)
ALTER TABLE public.b2b_products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.b2b_products
    FOR SELECT USING (true);

-- 실제 운영 환경에서는 아래 정책을 관리자 권한으로 제한하는 것이 좋습니다.
CREATE POLICY "Enable insert for all users" ON public.b2b_products
    FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.b2b_products
    FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON public.b2b_products
    FOR DELETE USING (true);

-- 2. Storage Bucket 생성 (이미지 저장용)
-- Supabase 대시보드에서 수동으로 생성해도 되지만, 아래 쿼리로도 생성 가능합니다.
INSERT INTO storage.buckets (id, name, public) 
VALUES ('products', 'products', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Object 정책 설정 (products 버킷에 대해 누구나 읽고 업로드 가능하도록 임시 허용)
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id = 'products');
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'products');
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING (bucket_id = 'products');
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING (bucket_id = 'products');
